-- DropForeignKey
ALTER TABLE "RFQ" DROP CONSTRAINT "RFQ_userId_fkey";

-- AlterTable
ALTER TABLE "RFQ" ALTER COLUMN "userId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "RFQ" ADD CONSTRAINT "RFQ_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
